feelings/feelings/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

from django.views.generic import TemplateView
from thoughts import urls as thought_urls
from users import urls as users_urls
from groups import urls as groups_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urls, namespace='users')),
    url(r'^groups/', include(groups_urls, namespace='groups')),
    url(r'^thoughts/', include(thought_urls, namespace='thoughts')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home')
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

feelings/users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url('^', include('django.contrib.auth.urls')),
]

feelings/thoughts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


CONDITIONS = (
    (0, 'Ecstatic'),
    (5, 'Passionate'),
    (10, 'Happy'),
    (15, 'Positive'),
    (20, 'Optimistic'),
    (25, 'Bored'),
    (26, 'Tired'),
    (27, 'Hungry'),
    (30, 'Pessimistic'),
    (35, 'Frustrated'),
    (40, 'Overwhelmed'),
    (45, 'Disappointed'),
    (50, 'Worried'),
    (55, 'Angry'),
    (60, 'Jealous'),
    (65, 'Insecure'),
    (70, 'Guilty'),
    (75, 'Fear'),
    (80, 'Grief'),
    (85, 'Despair'),
    (90, 'Paranoid'),
)


class Thought(models.Model):
    user = models.ForeignKey(User, related_name='thoughts')
    recorded_at = models.DateTimeField(default=timezone.now, editable=False)
    condition = models.IntegerField(choices=CONDITIONS)
    notes = models.TextField(default='', blank=True)

    def __str__(self):
        return '{}: {}'.format(self.recorded_at.strftime('%Y-%m-%d %H:%M:%S'), self.get_condition_display())

    class Meta:
        ordering = ['-recorded_at']

feelings/users/forms.py
from django import forms

from . import models


class LogoutForm(forms.Form):
    pass

feelings/users/views.py
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.views import generic
from django.http import HttpResponseRedirect

from braces.views import SelectRelatedMixin

from . import forms
from . import models


class Dashboard(
    LoginRequiredMixin,
    SelectRelatedMixin,
    generic.DetailView
):
    model = User
    select_related = ('thoughts',)
    template_name = 'users/dashboard.html'

    def get_object(self, queryset=None):
        return self.request.user


class LogoutView(LoginRequiredMixin, generic.FormView):
    form_class = forms.LogoutForm
    template_name = 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:dashboard')

feelings/users/templates/users/dashboard.html
{% extends 'layout.html' %}

{% load static from staticfiles %}

{% load thought_tags %}

{% block title %} Dashboard | {{ block.super }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Recent Thoughts</h2>
                <div class="list-group">
                    {% for thought in user.thoughts.all %}
                        <div class="list-group-item">
                            <h4 class="list-group-item-heading">
                                <time class="pull-right small" datetime="{{ thought.recorded_at }}">{{ thought.recorded_at | date:'SHORT_DATE_FORMAT' }}</time>
                                {{ thought.get_condition_display }}
                            </h4>
                            {% if thought.notes %} {{ thought.notes | linebreaks }} {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                {% thought_form %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="ct-chart ct-perfect-fourth"></div>
                {% chart_data as email %}
                {{ email }}
            </div>
            <div class="col-md-6">
                <h3>Companies</h3>
                <div class="list-group">
                    {% for company in user.companies.all %}
                        <a href="{% url 'groups:companies:detail' slug=company.slug %}" class="list-group-item">{{ company.name }}</a>
                    {% endfor %}
                </div>
                <h3>Families</h3>
                <div class="list-group">
                    {% for family in user.families.all %}
                        <a href="{% url 'groups:families:detail' slug=family.slug %}" class="list-group-item">{{ family.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'js/chartist/chartist.min.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'js/stretchy.js' %}" data-filter="#id_notes" async></script>
    <script src="{% static 'js/chartist/chartist.min.js' %}"></script>
    <script>
        {% chart_data as data %}
        var data = {{ data | safe }};
        new Chartist.Line('.ct-chart', data);
    </script>
{% endblock %}

feelings/users/templates/users/logout.html
{% extends 'layout.html' %}

{% block title %}
    Logout | {{ block.super }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>You sure?</h3>
            <form action="" method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-default">
            </form>
        </div>
        <div class="col-md-6">
            <h3>Come back soon!</h3>
            <p>This site works beast if you use it often!</p>
        </div>
    </div>
</div>
{% endblock %}

feelings/users/templates/users/signup.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block title %}
    Sign Up | {{ block.super }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Sign Up</h3>
            <form action="" method="post">
                {% bootstrap_form form %}
                {% csrf_token %}
                <input type="submit" value="Sign Up" class="btn btn-default">
            </form>
        </div>
        <div class="col-md-6">
            <h3>How are you feelings?</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At aut commodi dicta est excepturi exercitationem, facilis ipsum minus nemo officia quasi qui quisquam tenetur ullam veniam voluptatem voluptatibus. Facere, porro?</p>
        </div>
    </div>
</div>
{% endblock %}